AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:      
    EventBridgePublisherFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: eventbridgePublisher.handler
            FunctionName: 'demo-eventbridge-publisher'
            Runtime: nodejs12.x
            MemorySize: 256
            CodeUri: ./app
            Policies:
                - AmazonEventBridgeFullAccess
                - AWSLambdaBasicExecutionRole

    ProcessorFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: processor.handler
            FunctionName: 'demo-eventbridge-processor'
            Runtime: nodejs12.x
            MemorySize: 256
            CodeUri: ./app
