AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample App for HTTP API
Globals:
  Function:
    Timeout: 5

Resources:
    HTTPLambda:
        Type: AWS::Serverless::Function
        Properties:
            InlineCode: |
                exports.handler = async (event) => {
                    console.log(`events - ${JSON.stringify(event)}`)
                    return "Hello v2"
                };
            Handler: index.handler
            Runtime: nodejs12.x
            MemorySize: 256
            FunctionName: 'demo-httpapi-lambda'
            Role: <replace this>
            Events:
                HttpApiEvent:
                    Type: HttpApi # Using the new HTTP API here
                    Properties:
                        PayloadFormatVersion: "2.0"

    # NormalLambda:
    #     Type: AWS::Serverless::Function
    #     Properties:
    #         InlineCode: |
    #             exports.handler = async (event) => {
    #                 console.log(`events - ${JSON.stringify(event)}`)
    #                 return {'body': 'Hello World!', 'statusCode': 200}
    #             };
    #         Handler: index.handler
    #         Runtime: nodejs12.x
    #         MemorySize: 256
    #         FunctionName: 'demo-rest-lambda'
    #         Role: <replace this>
    #         Events:
    #             RestApiEvent:
    #                 Type: Api
    #                 Properties:
    #                     Path: /rest
    #                     Method: get


